name: tudat-bundle
channels:
  - conda-forge
  - tudat-team
dependencies:
  - eigen
  - boost-cpp=1.72
  - tudat-resources
  - sofa-cmake
  - cspice-cmake
  - python=3.8
  - pybind11
  - pybind11-abi
  - numpy
  - pytest