name: Linter 🔎

on: [push, pull_request]

jobs:
  c-lint:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}